title: Cogitare
author: Ronaldo Ferreira
description: Mescla de ideias.

highlighter: null
permalink: /:title

url:
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
